apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
  labels:
    app: spring-app
spec:
  type: ClusterIP
  ports:
    - port: 6001
      targetPort: 6001
  selector:
    app: spring-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: spring-app # Assumes you have built an image with this name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6001
